# Generated by Django 4.1.4 on 2022-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Messenger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_model",
            name="nickname",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name=(
                    {"username": "Ryska"},
                    {"username": "test1"},
                    {"username": "test2"},
                    {"username": "test3"},
                    {"username": "test4"},
                    {"username": "test5"},
                    {"username": "test6"},
                    {"username": "test7"},
                    {"username": "test8"},
                    {"username": "test9"},
                    {"username": "test10"},
                    {"username": "test11"},
                    {"username": "test12"},
                ),
            ),
        ),
    ]
