# Generated by Django 4.1.4 on 2022-12-14 15:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Messenger", "0002_user_model_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=100)),
                ("body", models.CharField(max_length=2000)),
                ("send_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user_model",
            name="nickname",
        ),
        migrations.AddField(
            model_name="user_model",
            name="blocked_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="user_model",
            name="chats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000, null=True),
                null=True,
                size=None,
            ),
        ),
    ]
