# Generated by Django 4.1.4 on 2023-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Messenger", "0005_user_model_delete_chatlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_model",
            name="profile_photo",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
