# Generated by Django 4.1.4 on 2023-01-06 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Messenger", "0007_alter_user_model_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_model",
            name="blocked_list",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="blocked_list",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user_model",
            name="chats",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="chats", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
