# Generated by Django 4.1.4 on 2023-01-08 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Messenger", "0011_alter_user_model_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="user_model",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="user_model",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
