# Generated by Django 4.1.4 on 2023-01-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Messenger", "0012_alter_message_receiver_alter_message_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_model",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="images/default_photo.jpg",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
