# Generated by Django 4.1.4 on 2023-01-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Messenger", "0016_alter_user_model_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="send_photos/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
