# Generated by Django 4.1.4 on 2023-01-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Messenger", "0019_mess_chat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
